[package]
name = "ls_boot"
version = "0.1.0"
edition = "2021"

[dependencies]
thing_std = { path = "../../crates/thing_std" }
thing_models = { package = "models", path = "../../../crates/models" }
serde = { workspace = true, features = ["derive"] }
postcard = { workspace = true }
abi = { path = "../../../crates/abi" }
