[workspace]
resolver = "2"
members = [
    "user/examples_support",
    "boot",
    "kernel",
    "abi",
    "runtime",
    "thing_os",
    "user/init",
    "user/debug_thread",
    "user/debug_clock",
    "user/debug_alarm",
    "user/mode_manager",
    "user/ps2_keyboard_driver",
    "user/ps2_mouse_driver",
    "user/debug_input_events",
    "user/debug_input_logger",
    "user/framebuffer_driver",
    "user/compositor",
    "user/window_demo",
    "hal",
    "drivers_usb",
    "drivers_pci",
    "user/rootfs",
    "user/geographer",
    "thing_macros",
    "thing_models",
    "smoke_tests",
    "arch",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
limine = "0.5"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
