[workspace]
resolver = "2"
members = [
    "boot",
    "kernel",
    "abi",
    "thing_os",
    "user/clock",
    "user/compositor",
    "user/compositor_api",
    "user/window_demo",
    "libs/hal",
    "user/drivers/usb",
    "user/drivers/pci",
    "thing_macros",
    "thing_models",
    "arch",
    "user/init",
    "user/drivers/framebuffer",
    "user/drivers/ps2_keyboard",
    "user/drivers/ps2_mouse",
    "user/geographer",

    "user/hello_world", "tools/icon-gen",
    "user/debug_alloc",
    "smoke_tests",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
limine = "0.5"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
