[workspace]
members = [
    "userspace/virtio_gpu",
    "userspace/virtio",
    "userspace/display_bootfb",
    "userspace/display_virtio_gpu",
    "userspace/display_fake",
    "bran",
    "xtask",
    "tools/bdd",
    "kernel",
    "abi",
    "stem",
    "stem-macros",

    "userspace/sprout",
    "userspace/rtc_cmos",
    "userspace/clock",
    "userspace/font_explorer",
    "userspace/ps2_kbd",
    "userspace/bristle",
    "userspace/ps2_mouse",
    "userspace/echo",
    "userspace/bloom",
    "userspace/ata_disk",
    "userspace/disk_probe",
    "userspace/ahci_disk",
    "tools/pciids",
    "userspace/cambium",
    "userspace/tick_printer",
    "userspace/hogger",
    "userspace/irqdump", "abi-macros",
    "userspace/root_batch_bench",
    "userspace/bench_blit",
    "userspace/root_watch_tester",
    "userspace/scheduler_fairness",
    "userspace/photosynthesis",
    "userspace/ingestd",
    "userspace/cambium",
    "userspace/fontd",
    "userspace/blossom",
    "userspace/drawlist_demo",
    "userspace/drawlist_validate",
    "userspace/virgl_demo",
    "userspace/iso9660",
    "userspace/iso9660d",
    "userspace/iso_reader",
    "userspace/iso_cat",
    "tools/display_proto_tests",
    "userspace/virtio_netd",
    "userspace/netd",
    "userspace/fetchd",
    "userspace/anther",
    "userspace/phloem",
    "bud",
    "libs/fb_common",
    "libs/llm",
    "libs/llm_stub",
    "userspace/described",
    "userspace/sysdescribe",
    "userspace/driver_wasm_host",
    "userspace/proto_driver_wasm",
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
