timeout: 0
quiet: yes
verbose: no
serial: yes

/ThingOS
    protocol: limine
    resolution: 1280x720
    kernel_path: boot():/boot/kernel
    module_path: boot():/boot/sprout
    module_path: boot():/boot/threads
    module_path: boot():/boot/rtc_cmos
    module_path: boot():/boot/clock
