timeout: 0
verbose: yes
quiet: no
serial: yes

/ThingOS
    protocol: limine
    resolution: 1280x720
    kernel_path: boot():/boot/kernel
    module_path: boot():/boot/modules/sprout
    module_path: boot():/boot/modules/bloom
    module_path: boot():/boot/modules/graph_smoke
    module_path: boot():/boot/modules/log_smoke
    module_path: boot():/boot/modules/cap_fail
    module_path: boot():/boot/modules/clock
    module_path: boot():/boot/modules/inputd
    module_path: boot():/boot/modules/echo
    module_path: boot():/boot/modules/inspector
    module_path: boot():/boot/modules/logview
