timeout: 0
quiet: yes

/Limine Template
    protocol: limine
    kernel_path: boot():/boot/kernel
    module_path: boot():/boot/user/init
    module_cmdline: program=init
    module_path: boot():/boot/user/debug_thread
    module_cmdline: program=debug_thread
    module_path: boot():/boot/user/debug_clock
    module_cmdline: program=debug_clock
    module_path: boot():/boot/user/debug_alarm
    module_cmdline: program=debug_alarm
    module_path: boot():/boot/drivers/framebuffer_driver
    module_cmdline: program=framebuffer_driver
    module_path: boot():/boot/drivers/ps2_keyboard_driver
    module_cmdline: program=ps2_keyboard_driver
    module_path: boot():/boot/drivers/ps2_mouse_driver
    module_cmdline: program=ps2_mouse_driver
    module_path: boot():/boot/user/compositor
    module_cmdline: program=compositor
    module_path: boot():/boot/user/debug_input_logger
    module_cmdline: program=debug_input_logger
    module_path: boot():/boot/user/debug_input_events
    module_cmdline: program=debug_input_events
    module_path: boot():/boot/user/window_demo
    module_cmdline: program=window_demo
    module_path: boot():/boot/user/mode_manager
    module_cmdline: program=mode_manager

    module_path: boot():/boot/clouds.bmp
    module_cmdline: image=clouds.bmp
