[package]
name = "debug_thread"
version.workspace = true
edition.workspace = true

[lib]
name = "debug_thread"
path = "src/lib.rs"

[dependencies]
thing_os = { path = "../../thing_os" }
runtime = { path = "../../runtime" }

[dev-dependencies]
kernel = { path = "../../kernel" }
abi = { path = "../../abi" }
thing_models = { path = "../../thing_models" }
