[package]
name = "kernel"
version = "0.2.0"
edition.workspace = true
license.workspace = true

[dependencies]

thing_models = { package = "models", path = "../models" }
abi = { path = "../abi" }
spin = "0.9.8"
heapless = "0.8.0"
postcard = { workspace = true, features = ["alloc"] }
serde = { workspace = true, features = ["derive"] }
xmas-elf = { version = "0.9", default-features = false }
boot = { path = "../boot" }
