[package]
name = "boot"
version.workspace = true
edition.workspace = true

[features]
boot-dashboard-only = []

[dependencies]
limine.workspace = true
kernel_core = { path = "../kernel_core" }
abi = { path = "../abi" }
userland_rt = { path = "../userland_rt", features = ["kernel"] }
user_app_hello = { path = "../user_app_hello" }
user_app_heartbeat = { path = "../user_app_heartbeat" }
user_app_init = { path = "../user_app_init" }
user_app_thread_dashboard = { path = "../user_app_thread_dashboard" }
lazy_static = { version = "1.4", features = ["spin_no_std"] }
spin = "0.10.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.14"

[build-dependencies]
reqwest = { version = "0.12", default-features = false, features = [
    "blocking",
    "rustls-tls",
] }
flate2 = "1.0"
