[package]
name = "boot"
version.workspace = true
edition.workspace = true

[dependencies]
limine.workspace = true
kernel_core = { path = "../kernel_core" }
abi = { path = "../abi" }
userland_rt = { path = "../userland_rt", features = ["kernel"] }
user_app_hello = { path = "../user_app_hello" }
user_app_heartbeat = { path = "../user_app_heartbeat" }

[build-dependencies]
reqwest = { version = "0.12", default-features = false, features = [
    "blocking",
    "rustls-tls",
] }
flate2 = "1.0"
