[package]
name = "thing_os"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
abi = { path = "../abi" }
allocator-api2 = { version = "0.2.21", default-features = false, features = ["alloc"] }

spin = "0.9.8"
thing_models = { path = "../thing_models" }
thing_macros = { path = "../thing_macros" }
linked_list_allocator = "0.9"

# No runtime dependency anymore
