[package]
name = "timed"
version = "0.1.0"
edition = "2021"

[dependencies]
thing_std = { path = "../../crates/thing_std" }
thing_derive = { path = "../../crates/thing_derive" }
thing_codec = { path = "../../crates/thing_codec" }
abi = { path = "../../crates/abi" }
models = { path = "../../crates/models" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
alloc = { package = "rust-freestanding-alloc", version = "0.1" }
