[package]
name = "xtask"
version = "0.2.0"
edition.workspace = true
license.workspace = true

[dependencies]
models = { path = "../crates/models" }
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
ttf-parser = "0.25"
postcard = { version = "1.0", features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
