// Generated by xtask ontology
// SymbolId and ThingId are imported in lib.rs via abi::ids
// Vec is imported in lib.rs

pub trait Thing {
    fn kind(&self) -> SymbolId;
    fn schema(&self) -> SymbolId;
    fn version(&self) -> u32;
    fn encode(&self) -> Vec<u8>;
    fn decode(bytes: &[u8]) -> Result<Self, ()> where Self: Sized;
}

impl Thing for BytespaceBody {
    fn kind(&self) -> SymbolId { SymbolId(0xF8FCB00535E9A405) }
    fn schema(&self) -> SymbolId { SymbolId(0xBDFCE06BB86A2CFF) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.len.to_le_bytes());
        bytes.extend_from_slice(&self.flags.to_le_bytes());
        bytes.extend_from_slice(&self._pad.to_le_bytes());
        bytes.extend_from_slice(&self.phys_base.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let len = u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?);
        offset += 8;
        let flags = u32::from_le_bytes(bytes[offset..offset+4].try_into().map_err(|_| ())?);
        offset += 4;
        let _pad = u32::from_le_bytes(bytes[offset..offset+4].try_into().map_err(|_| ())?);
        offset += 4;
        let phys_base = u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?);
        offset += 8;
        Ok(Self {
            len,
            flags,
            _pad,
            phys_base,
        })
    }
}

impl Thing for MonotonicClockBody {
    fn kind(&self) -> SymbolId { SymbolId(0x92F5EACE38FBFE15) }
    fn schema(&self) -> SymbolId { SymbolId(0xFB520DC25492C05) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.now_ns.to_le_bytes());
        bytes.extend_from_slice(&self.resolution_ns.to_le_bytes());
        bytes.extend_from_slice(&self.source.0.to_le_bytes());
        bytes.extend_from_slice(&self.last_update_ns.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let now_ns = u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?);
        offset += 8;
        let resolution_ns = u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?);
        offset += 8;
        let source = SymbolId(u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?));
        offset += 8;
        let last_update_ns = u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?);
        offset += 8;
        Ok(Self {
            now_ns,
            resolution_ns,
            source,
            last_update_ns,
        })
    }
}

impl Thing for PlaceBody {
    fn kind(&self) -> SymbolId { SymbolId(0x43E7C812F1795346) }
    fn schema(&self) -> SymbolId { SymbolId(0xBE52087A23A917F0) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.name.0.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let name = SymbolId(u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?));
        offset += 8;
        Ok(Self {
            name,
        })
    }
}

impl Thing for RelationshipBody {
    fn kind(&self) -> SymbolId { SymbolId(0x4F308BFD270391BD) }
    fn schema(&self) -> SymbolId { SymbolId(0x37391EE2FEA08FE9) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.from.0.to_le_bytes());
        bytes.extend_from_slice(&self.to.0.to_le_bytes());
        bytes.extend_from_slice(&self.predicate.0.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let from = ThingId(u128::from_le_bytes(bytes[offset..offset+16].try_into().map_err(|_| ())?));
        offset += 16;
        let to = ThingId(u128::from_le_bytes(bytes[offset..offset+16].try_into().map_err(|_| ())?));
        offset += 16;
        let predicate = SymbolId(u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?));
        offset += 8;
        Ok(Self {
            from,
            to,
            predicate,
        })
    }
}

impl Thing for SurfaceBody {
    fn kind(&self) -> SymbolId { SymbolId(0x4630246DF0D3FF22) }
    fn schema(&self) -> SymbolId { SymbolId(0x55E5957BEA5E14D8) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.width.to_le_bytes());
        bytes.extend_from_slice(&self.height.to_le_bytes());
        bytes.extend_from_slice(&self.stride_bytes.to_le_bytes());
        bytes.extend_from_slice(&self.format.0.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let width = u32::from_le_bytes(bytes[offset..offset+4].try_into().map_err(|_| ())?);
        offset += 4;
        let height = u32::from_le_bytes(bytes[offset..offset+4].try_into().map_err(|_| ())?);
        offset += 4;
        let stride_bytes = u32::from_le_bytes(bytes[offset..offset+4].try_into().map_err(|_| ())?);
        offset += 4;
        let format = SymbolId(u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?));
        offset += 8;
        Ok(Self {
            width,
            height,
            stride_bytes,
            format,
        })
    }
}

impl Thing for SystemClockBody {
    fn kind(&self) -> SymbolId { SymbolId(0xA8EE901286E7C6A8) }
    fn schema(&self) -> SymbolId { SymbolId(0x5B3976096331339E) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.unix_epoch_ns.to_le_bytes());
        bytes.extend_from_slice(&self.status.to_le_bytes());
        bytes.extend_from_slice(&self._pad.to_le_bytes());
        bytes.extend_from_slice(&self.last_set_mono_ns.to_le_bytes());
        bytes.extend_from_slice(&self.accuracy_ns.to_le_bytes());
        bytes.extend_from_slice(&self.source.0.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let unix_epoch_ns = u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?);
        let unix_epoch_ns = unix_epoch_ns as i64;
        offset += 8;
        let status = u32::from_le_bytes(bytes[offset..offset+4].try_into().map_err(|_| ())?);
        offset += 4;
        let _pad = u32::from_le_bytes(bytes[offset..offset+4].try_into().map_err(|_| ())?);
        offset += 4;
        let last_set_mono_ns = u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?);
        offset += 8;
        let accuracy_ns = u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?);
        offset += 8;
        let source = SymbolId(u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?));
        offset += 8;
        Ok(Self {
            unix_epoch_ns,
            status,
            _pad,
            last_set_mono_ns,
            accuracy_ns,
            source,
        })
    }
}

impl Thing for TimeOffsetBody {
    fn kind(&self) -> SymbolId { SymbolId(0xCE1B548697AFA261) }
    fn schema(&self) -> SymbolId { SymbolId(0x32CF808760BD0A51) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.offset_ns.to_le_bytes());
        bytes.extend_from_slice(&self.rate_ppb.to_le_bytes());
        bytes.extend_from_slice(&self.updated_mono_ns.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let offset_ns = u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?);
        let offset_ns = offset_ns as i64;
        offset += 8;
        let rate_ppb = u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?);
        let rate_ppb = rate_ppb as i64;
        offset += 8;
        let updated_mono_ns = u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?);
        offset += 8;
        Ok(Self {
            offset_ns,
            rate_ppb,
            updated_mono_ns,
        })
    }
}

