// Generated by xtask ontology
// SymbolId and ThingId are imported in lib.rs via abi::ids
// Vec is imported in lib.rs

pub trait Thing {
    fn kind(&self) -> SymbolId;
    fn schema(&self) -> SymbolId;
    fn version(&self) -> u32;
    fn encode(&self) -> Vec<u8>;
    fn decode(bytes: &[u8]) -> Result<Self, ()> where Self: Sized;
}

fn read<const N: usize>(bytes: &[u8], offset: &mut usize) -> Result<[u8; N], ()> {
    let end = offset.checked_add(N).ok_or(())?;
    let slice = bytes.get(*offset..end).ok_or(())?;
    let chunk: [u8; N] = slice.try_into().map_err(|_| ())?;
    *offset = end;
    Ok(chunk)
}

impl Thing for BytespaceBody {
    fn kind(&self) -> SymbolId { SymbolId(0xF8FCB00535E9A405) }
    fn schema(&self) -> SymbolId { SymbolId(0xBDFCE06BB86A2CFF) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.len.to_le_bytes());
        bytes.extend_from_slice(&self.flags.to_le_bytes());
        bytes.extend_from_slice(&self._pad.to_le_bytes());
        bytes.extend_from_slice(&self.phys_base.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let len = u64::from_le_bytes(read::<8>(bytes, &mut offset)?);
        let flags = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let _pad = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let phys_base = u64::from_le_bytes(read::<8>(bytes, &mut offset)?);
        let _ = offset;
        Ok(Self {
            len,
            flags,
            _pad,
            phys_base,
        })
    }
}

impl Thing for DisplayDeviceBody {
    fn kind(&self) -> SymbolId { SymbolId(0x46F9CB5BBE36FC35) }
    fn schema(&self) -> SymbolId { SymbolId(0x9A57E89E659D49AB) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.framebuffer.0.to_le_bytes());
        bytes.extend_from_slice(&self.width.to_le_bytes());
        bytes.extend_from_slice(&self.height.to_le_bytes());
        bytes.extend_from_slice(&self.stride_bytes.to_le_bytes());
        bytes.extend_from_slice(&self.format.0.to_le_bytes());
        bytes.extend_from_slice(&self.refresh_hz.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let framebuffer = ThingId(u128::from_le_bytes(read::<16>(bytes, &mut offset)?));
        let width = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let height = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let stride_bytes = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let format = SymbolId(u64::from_le_bytes(read::<8>(bytes, &mut offset)?));
        let refresh_hz = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let _ = offset;
        Ok(Self {
            framebuffer,
            width,
            height,
            stride_bytes,
            format,
            refresh_hz,
        })
    }
}

impl Thing for FramebufferBody {
    fn kind(&self) -> SymbolId { SymbolId(0x39F61C14D039B916) }
    fn schema(&self) -> SymbolId { SymbolId(0x2BD6128606BA3300) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.bytespace.0.to_le_bytes());
        bytes.extend_from_slice(&self.width.to_le_bytes());
        bytes.extend_from_slice(&self.height.to_le_bytes());
        bytes.extend_from_slice(&self.stride_bytes.to_le_bytes());
        bytes.extend_from_slice(&self.format.0.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let bytespace = ThingId(u128::from_le_bytes(read::<16>(bytes, &mut offset)?));
        let width = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let height = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let stride_bytes = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let format = SymbolId(u64::from_le_bytes(read::<8>(bytes, &mut offset)?));
        let _ = offset;
        Ok(Self {
            bytespace,
            width,
            height,
            stride_bytes,
            format,
        })
    }
}

impl Thing for MonotonicClockBody {
    fn kind(&self) -> SymbolId { SymbolId(0x92F5EACE38FBFE15) }
    fn schema(&self) -> SymbolId { SymbolId(0xFB520DC25492C05) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.now_ns.to_le_bytes());
        bytes.extend_from_slice(&self.resolution_ns.to_le_bytes());
        bytes.extend_from_slice(&self.source.0.to_le_bytes());
        bytes.extend_from_slice(&self.last_update_ns.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let now_ns = u64::from_le_bytes(read::<8>(bytes, &mut offset)?);
        let resolution_ns = u64::from_le_bytes(read::<8>(bytes, &mut offset)?);
        let source = SymbolId(u64::from_le_bytes(read::<8>(bytes, &mut offset)?));
        let last_update_ns = u64::from_le_bytes(read::<8>(bytes, &mut offset)?);
        let _ = offset;
        Ok(Self {
            now_ns,
            resolution_ns,
            source,
            last_update_ns,
        })
    }
}

impl Thing for MouseStreamBody {
    fn kind(&self) -> SymbolId { SymbolId(0x5EF2B03692E82DBA) }
    fn schema(&self) -> SymbolId { SymbolId(0x38E3155E669F1A50) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.bytespace.0.to_le_bytes());
        bytes.extend_from_slice(&self.capacity.to_le_bytes());
        bytes.extend_from_slice(&self.sample_size.to_le_bytes());
        bytes.extend_from_slice(&self.write_index.to_le_bytes());
        bytes.extend_from_slice(&self.dropped.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let bytespace = ThingId(u128::from_le_bytes(read::<16>(bytes, &mut offset)?));
        let capacity = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let sample_size = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let write_index = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let dropped = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let _ = offset;
        Ok(Self {
            bytespace,
            capacity,
            sample_size,
            write_index,
            dropped,
        })
    }
}

impl Thing for PlaceBody {
    fn kind(&self) -> SymbolId { SymbolId(0x43E7C812F1795346) }
    fn schema(&self) -> SymbolId { SymbolId(0xBE52087A23A917F0) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.name.0.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let name = SymbolId(u64::from_le_bytes(read::<8>(bytes, &mut offset)?));
        let _ = offset;
        Ok(Self {
            name,
        })
    }
}

impl Thing for PointerStateBody {
    fn kind(&self) -> SymbolId { SymbolId(0xFA3502E3D80D3979) }
    fn schema(&self) -> SymbolId { SymbolId(0x2B4B16B6345331BD) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.stream.0.to_le_bytes());
        bytes.extend_from_slice(&self.x.to_le_bytes());
        bytes.extend_from_slice(&self.y.to_le_bytes());
        bytes.extend_from_slice(&self.buttons.to_le_bytes());
        bytes.extend_from_slice(&self.updated_at_ns.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let stream = ThingId(u128::from_le_bytes(read::<16>(bytes, &mut offset)?));
        let x = i32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let y = i32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let buttons = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let updated_at_ns = u64::from_le_bytes(read::<8>(bytes, &mut offset)?);
        let _ = offset;
        Ok(Self {
            stream,
            x,
            y,
            buttons,
            updated_at_ns,
        })
    }
}

impl Thing for RelationshipBody {
    fn kind(&self) -> SymbolId { SymbolId(0x4F308BFD270391BD) }
    fn schema(&self) -> SymbolId { SymbolId(0x37391EE2FEA08FE9) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.from.0.to_le_bytes());
        bytes.extend_from_slice(&self.to.0.to_le_bytes());
        bytes.extend_from_slice(&self.predicate.0.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let from = ThingId(u128::from_le_bytes(read::<16>(bytes, &mut offset)?));
        let to = ThingId(u128::from_le_bytes(read::<16>(bytes, &mut offset)?));
        let predicate = SymbolId(u64::from_le_bytes(read::<8>(bytes, &mut offset)?));
        let _ = offset;
        Ok(Self {
            from,
            to,
            predicate,
        })
    }
}

impl Thing for SurfaceBody {
    fn kind(&self) -> SymbolId { SymbolId(0x4630246DF0D3FF22) }
    fn schema(&self) -> SymbolId { SymbolId(0x55E5957BEA5E14D8) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.width.to_le_bytes());
        bytes.extend_from_slice(&self.height.to_le_bytes());
        bytes.extend_from_slice(&self.stride_bytes.to_le_bytes());
        bytes.extend_from_slice(&self.format.0.to_le_bytes());
        bytes.extend_from_slice(&self.bytespace.0.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let width = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let height = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let stride_bytes = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let format = SymbolId(u64::from_le_bytes(read::<8>(bytes, &mut offset)?));
        let bytespace = ThingId(u128::from_le_bytes(read::<16>(bytes, &mut offset)?));
        let _ = offset;
        Ok(Self {
            width,
            height,
            stride_bytes,
            format,
            bytespace,
        })
    }
}

impl Thing for SystemClockBody {
    fn kind(&self) -> SymbolId { SymbolId(0xA8EE901286E7C6A8) }
    fn schema(&self) -> SymbolId { SymbolId(0x5B3976096331339E) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.unix_epoch_ns.to_le_bytes());
        bytes.extend_from_slice(&self.status.to_le_bytes());
        bytes.extend_from_slice(&self._pad.to_le_bytes());
        bytes.extend_from_slice(&self.last_set_mono_ns.to_le_bytes());
        bytes.extend_from_slice(&self.accuracy_ns.to_le_bytes());
        bytes.extend_from_slice(&self.source.0.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let unix_epoch_ns = i64::from_le_bytes(read::<8>(bytes, &mut offset)?);
        let status = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let _pad = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let last_set_mono_ns = u64::from_le_bytes(read::<8>(bytes, &mut offset)?);
        let accuracy_ns = u64::from_le_bytes(read::<8>(bytes, &mut offset)?);
        let source = SymbolId(u64::from_le_bytes(read::<8>(bytes, &mut offset)?));
        let _ = offset;
        Ok(Self {
            unix_epoch_ns,
            status,
            _pad,
            last_set_mono_ns,
            accuracy_ns,
            source,
        })
    }
}

impl Thing for TimeOffsetBody {
    fn kind(&self) -> SymbolId { SymbolId(0xCE1B548697AFA261) }
    fn schema(&self) -> SymbolId { SymbolId(0x32CF808760BD0A51) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.offset_ns.to_le_bytes());
        bytes.extend_from_slice(&self.rate_ppb.to_le_bytes());
        bytes.extend_from_slice(&self.updated_mono_ns.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let offset_ns = i64::from_le_bytes(read::<8>(bytes, &mut offset)?);
        let rate_ppb = i64::from_le_bytes(read::<8>(bytes, &mut offset)?);
        let updated_mono_ns = u64::from_le_bytes(read::<8>(bytes, &mut offset)?);
        let _ = offset;
        Ok(Self {
            offset_ns,
            rate_ppb,
            updated_mono_ns,
        })
    }
}

impl Thing for WindowBody {
    fn kind(&self) -> SymbolId { SymbolId(0x2AEC7E1B886B5C47) }
    fn schema(&self) -> SymbolId { SymbolId(0x939AA0A705967517) }
    fn version(&self) -> u32 { 1 }
    fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.surface.0.to_le_bytes());
        bytes.extend_from_slice(&self.x.to_le_bytes());
        bytes.extend_from_slice(&self.y.to_le_bytes());
        bytes.extend_from_slice(&self.width.to_le_bytes());
        bytes.extend_from_slice(&self.height.to_le_bytes());
        bytes.extend_from_slice(&self.z.to_le_bytes());
        bytes.extend_from_slice(&self.title.0.to_le_bytes());
        bytes
    }
    fn decode(bytes: &[u8]) -> Result<Self, ()> {
        let mut offset = 0;
        let surface = ThingId(u128::from_le_bytes(read::<16>(bytes, &mut offset)?));
        let x = i32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let y = i32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let width = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let height = u32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let z = i32::from_le_bytes(read::<4>(bytes, &mut offset)?);
        let title = SymbolId(u64::from_le_bytes(read::<8>(bytes, &mut offset)?));
        let _ = offset;
        Ok(Self {
            surface,
            x,
            y,
            width,
            height,
            z,
            title,
        })
    }
}

