[package]
name = "usb_xhci"
version = "0.1.0"
edition = "2021"

[dependencies]
abi = { path = "../../crates/abi" }
# log = { path = "../../kernel/src/log" } 
# Better to pass a logger or use alloc::format.
thing_std = { path = "../../crates/thing_std", optional = true } 

[features]
default = ["std"]
std = ["thing_std"]
