[package]
name = "alarm_demo"
version.workspace = true
edition.workspace = true

[lib]
name = "alarm_demo"
path = "src/lib.rs"

[dependencies]
userland = { path = "../../userland" }
runtime = { path = "../../runtime" }

[dev-dependencies]
kernel = { path = "../../kernel" }
abi = { path = "../../abi" }
userland_std = { path = "../../userland_std" }
thing_models = { path = "../../thing_models" }
