[package]
name = "alarm_demo"
version.workspace = true
edition.workspace = true

[lib]
name = "alarm_demo"
path = "src/lib.rs"

[dependencies]
userland = { path = "../../userland" }
userland_rt = { path = "../../userland_rt" }

[dev-dependencies]
kernel_core = { path = "../../kernel_core" }
abi = { path = "../../abi" }
