[package]
name = "fontd"
version = "0.1.0"
edition = "2021"

[dependencies]
stem = { path = "../../stem", features = ["rt"] }
abi = { path = "../../abi" }
fontdue = { version = "0.9", default-features = false, features = ["hashbrown"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc", "rc"] }
spin = "0.10.0"
