[package]
name = "fontd"
version = "0.1.0"
edition = "2021"

[dependencies]
stem = { path = "../../stem", features = ["rt", "global-alloc"] }
abi = { path = "../../abi" }
log = "0.4.17"
fontdue = { version = "0.9", default-features = false, features = ["hashbrown"] }
ttf-parser = { version = "0.25", default-features = false, features = ["no-std-float"] }
hashbrown = { version = "0.14", default-features = false, features = ["ahash", "inline-more"] }
