timeout: 0
serial: yes
verbose: yes

/ThingOS
    protocol: limine
    resolution: 1280x720
    kernel_path: boot():/boot/kernel

    module_path: boot():/boot/modules/graph_dump
    module_string: graph_dump
    module_path: boot():/boot/modules/ps2_keyboard
    module_string: ps2_keyboard
    module_path: boot():/boot/modules/ps2_mouse
    module_string: ps2_mouse
    module_path: boot():/boot/modules/keylog
    module_string: keylog
    module_path: boot():/boot/fonts/NotoSans-Regular.ttf
    module_string: NotoSans-Regular.ttf
    module_path: boot():/boot/fonts/NotoSerif-Regular.ttf
    module_string: NotoSerif-Regular.ttf
    module_path: boot():/boot/fonts/NotoSansSymbol-Regular.ttf
    module_string: NotoSansSymbol-Regular.ttf
    module_path: boot():/boot/fonts/NotoSansSymbol2-Regular.ttf
    module_string: NotoSansSymbol2-Regular.ttf
    module_path: boot():/boot/modules/syscall_crud_smoke
    module_string: syscall_crud_smoke
    module_path: boot():/boot/modules/clock
    module_string: clock
    module_path: boot():/boot/modules/sleep_smoke
    module_string: sleep_smoke
    module_path: boot():/boot/modules/rtc_x86
    module_string: rtc_x86
    module_path: boot():/boot/modules/rtc_aarch64
    module_string: rtc_aarch64
    module_path: boot():/boot/modules/sleep_accuracy_smoke
    module_string: sleep_accuracy_smoke



/ThingOS Smoke Mode
    protocol: limine
    resolution: 1280x720
    kernel_path: boot():/boot/kernel
    cmdline: thingos.smoke=syscall_crud_smoke

    module_path: boot():/boot/modules/graph_dump
    module_string: graph_dump
    module_path: boot():/boot/modules/ps2_keyboard
    module_string: ps2_keyboard
    module_path: boot():/boot/modules/ps2_mouse
    module_string: ps2_mouse
    module_path: boot():/boot/modules/keylog
    module_string: keylog
    module_path: boot():/boot/fonts/NotoSans-Regular.ttf
    module_string: NotoSans-Regular.ttf
    module_path: boot():/boot/fonts/NotoSerif-Regular.ttf
    module_string: NotoSerif-Regular.ttf
    module_path: boot():/boot/fonts/NotoSansSymbol-Regular.ttf
    module_string: NotoSansSymbol-Regular.ttf
    module_path: boot():/boot/fonts/NotoSansSymbol2-Regular.ttf
    module_string: NotoSansSymbol2-Regular.ttf
    module_path: boot():/boot/modules/syscall_crud_smoke
    module_string: syscall_crud_smoke
    module_path: boot():/boot/modules/clock
    module_string: clock
    module_path: boot():/boot/modules/sleep_smoke
    module_string: sleep_smoke
    module_path: boot():/boot/modules/rtc_x86
    module_string: rtc_x86
    module_path: boot():/boot/modules/rtc_aarch64
    module_string: rtc_aarch64
    module_path: boot():/boot/modules/sleep_accuracy_smoke
    module_string: sleep_accuracy_smoke
