timeout: 0
serial: yes
verbose: yes

/ThingOS
    protocol: limine
    resolution: 1280x720
    kernel_path: boot():/boot/kernel
    module_path: boot():/boot/modules/clock
    module_string: clock
    module_path: boot():/boot/modules/graph_dump
    module_string: graph_dump
