[package]
name = "kernel"
version.workspace = true
edition.workspace = true

[lib]

[features]
arch_pci_in_kernel = []
debug_logging = []
default = ["arch_pci_in_kernel"]

[dependencies]
abi = { path = "../abi" }
hal = { path = "../hal" }
drivers_usb = { path = "../drivers_usb" }
drivers_pci = { path = "../drivers_pci" }
thing_models = { path = "../thing_models" }
thing_macros = { path = "../thing_macros" }
heapless = "0.9.2"
spin = "0.10.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.14"

[build-dependencies]
reqwest = { version = "0.12", default-features = false, features = [
    "blocking",
    "rustls-tls",
] }
flate2 = "1.0"
