[package]
name = "thing_std"
version = "0.1.0"
edition = "2021"

[dependencies]
abi = { path = "../abi", default-features = false }
thing_codec = { path = "../thing_codec", default-features = false, features = ["alloc"] }
models = { path = "../models" }
symbols = { path = "../symbols" }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
postcard = { version = "1.0", default-features = false, features = ["alloc"] }
