[package]
name = "framebuffer"
version = "0.1.0"
edition = "2021"

[lib]
name = "framebuffer"
path = "src/lib.rs"

[dependencies]
thing_models = { path = "../../../thing_models" }
thing_macros = { path = "../../../thing_macros" }

thing_os = { path = "../../../thing_os" }
abi = { path = "../../../abi" }

[dev-dependencies]
kernel = { path = "../../../kernel" }
