[package]
name = "framebuffer"
version = "0.1.0"
edition = "2021"

[lib]
name = "framebuffer"
path = "src/lib.rs"

[dependencies]

thing_os = { path = "../../../thing_os" }
abi = { path = "../../../abi" }
thing_models = { path = "../../../thing_models" }

[dev-dependencies]
kernel = { path = "../../../kernel" }
