[package]
name = "bloom"
version = "0.1.0"
edition = "2021"

[features]
default = []
shadows = []

[dependencies]
abi = { path = "../abi" }
thing_std = { path = "../thing_std" }
models = { path = "../models" }
symbols = { path = "../symbols" }
tinybmp = "0.6.0"
png-decoder = "0.1.1"
micromath = "2.0.0"
fontdue = { version = "0.9", default-features = false, features = ["hashbrown"] }
spin = { version = "0.9", default-features = false, features = ["once"] }
postcard = { version = "1.0", features = ["alloc"], default-features = false }
