pub const BUILTIN_SYMBOLS: &[&str] = &[
    // meta
    "Kind",
    "Schema",
    "Link",
    "Intent",
    "Observation",
    "Result",
    // core-ish
    "TimeNow",
    "Process",
    "Thread",
    "Capability",
    "Graph",
    "Mount",
    "GraphProvider",
    "Buffer",
    "Stream",
    "Keyboard",
    "KeyEvent",
    "Font",
    "BootProgram",
    "BootRoot",
    // predicates
    "OWNS",
    "HAS_CAP",
    "HAS_SCHEMA",
    "HAS_META",
    "MOUNTS",
    "BACKED_BY",
    "LAUNCHES",
    // common fields (for future query tools)
    "name",
    "version",
    "created_at_ns",
    "created_by",
    "last_modified_at_ns",
    "last_modified_by",
    "owner",
    // Missing Predicates
    "HAS_CONSOLE",
    "HAS_BLOCK_DEVICE",
    "HAS_VOLUME",
    "HAS_MOUNT",
    "HAS_ENTRY",
    "ON_VOLUME",
    "BACKED_BY_DEVICE",
    "IS_MOUNTED_ON",
    "CONTAINS_FILE",
    "HAS_KEYBOARD",
    "HAS_TIME_NOW",
    "HAS_DEVICE",
    "SPAWNED",
    "RUNS",
    "HAS_MODULE",
    "BINARY_IMAGE",
    "ASSET",
    "PROVIDES_FONT",
    "DEFAULT_FONT",
    "USES_MODULE",
    // Missing Device/GraphFS Kinds
    "PciDevice",
    "SerialPort",
    "LogStream",
    "BlockDevice",
    "FileSystem",
    "File",
    "Dir",
    "Volume",
    // Missing Diag
    "LogEntry",
    "Error",
    "Fault",
];
