[package]
name = "debug_alarm"
version.workspace = true
edition.workspace = true

[lib]
name = "debug_alarm"
path = "src/lib.rs"

[dependencies]
runtime = { path = "../../runtime" }
thing_os = { path = "../../thing_os" }

[dev-dependencies]
kernel = { path = "../../kernel" }
abi = { path = "../../abi" }
thing_os = { path = "../../thing_os" }
thing_models = { path = "../../thing_models" }
