[package]
name = "framebuffer_driver"
version.workspace = true
edition.workspace = true

[lib]
name = "framebuffer_driver"
path = "src/lib.rs"

[dependencies]
userland = { path = "../../userland" }
userland_rt = { path = "../../userland_rt" }
abi = { path = "../../abi" }
userland_std = { path = "../../userland_std" }

[dev-dependencies]
kernel = { path = "../../kernel" }
