[package]
name = "framebuffer_driver"
version.workspace = true
edition.workspace = true

[lib]
name = "framebuffer_driver"
path = "src/lib.rs"

[dependencies]
userland = { path = "../../userland" }
runtime = { path = "../../runtime" }
abi = { path = "../../abi" }
thing_os = { path = "../../thing_os" }

[dev-dependencies]
kernel = { path = "../../kernel" }
