[alias]
xtask = "run --package xtask --"

[env]
RUST_TARGET_PATH = { value = "targets", relative = true }

[target.x86_64-thingos-unknown]
rustflags = ["-C", "relocation-model=static", "-C", "link-arg=-no-pie"]

[target.aarch64-thingos-unknown]
rustflags = ["-C", "relocation-model=static"]

[target.riscv64-thingos-unknown]
rustflags = ["-C", "relocation-model=static"]

[target.loongarch64-thingos-unknown]
rustflags = ["-C", "relocation-model=static"]

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
