#![no_std]
#![no_main]

//! # Network Service (netd) — Phase 3: /net/ VFS provider
//!
//! Replaces the graph-based driver IPC and port-based socket API with:
//! - Driver access via `/dev/net/virtio0/{rx,tx,mac,mtu}` VFS files (issue #540)
//! - Application socket API via `/net/` VFS tree (issue #541)

#[macro_use]
extern crate alloc;
extern crate stem;

mod dhcp;
mod dns;
mod socket_api;
mod vfs_device;
mod vfs_provider;

use smoltcp::iface::{Config, Interface, SocketSet, SocketStorage};
use smoltcp::wire::EthernetAddress;
use socket_api::SocketApi;
use stem::{info, warn};
use vfs_device::VfsNicDevice;
use vfs_provider::NetVfsProvider;

#[stem::main]
fn main(_arg: usize) -> ! {
    info!("NETD: Starting network service (Phase 3 — /net/ VFS provider)");

    // ── Open the driver VFS tree ──────────────────────────────────────────────
    // VfsNicDevice retries until virtio_netd has mounted /dev/net/virtio0/.
    info!("NETD: Waiting for /dev/net/virtio0 to appear...");
    let mut device = VfsNicDevice::open();

    let mac = device.mac();
    let mtu = device.mtu();
    let initial_link_up = device.link_up();

    info!(
        "NETD: Driver online — MAC {:02x}:{:02x}:{:02x}:{:02x}:{:02x}:{:02x}  MTU {}",
        mac[0], mac[1], mac[2], mac[3], mac[4], mac[5],
        mtu
    );

    // ── Build smoltcp interface ───────────────────────────────────────────────
    let mac_addr = EthernetAddress(mac);
    let config = Config::new(mac_addr.into());
    let mut iface = Interface::new(config, &mut device, VfsNicDevice::now());

    // ── Mount /net/ VFS provider ──────────────────────────────────────────────
    let mut net_provider = loop {
        match NetVfsProvider::new(mac, mtu, initial_link_up) {
            Some(p) => break p,
            None => {
                warn!("NETD: Failed to mount /net/, retrying...");
                stem::time::sleep_ms(200);
            }
        }
    };

    // ── Run DHCP ──────────────────────────────────────────────────────────────
    info!("NETD: Running DHCP...");
    let dhcp_config = match dhcp::run_dhcp(&mut iface, &mut device) {
        Ok(cfg) => {
            info!(
                "NETD: DHCP — IP: {}, GW: {}, DNS: {}",
                cfg.ip, cfg.gateway, cfg.dns
            );
            cfg
        }
        Err(e) => {
            warn!("NETD: DHCP failed: {:?}", e);
            loop {
                stem::time::sleep_ms(1000);
            }
        }
    };

    // ── Publish IP config to /net/ provider ───────────────────────────────────
    net_provider.set_ip_config(dhcp_config.ip, dhcp_config.prefix_len, dhcp_config.gateway);

    info!("NETD: Network ready — entering VFS service loop");

    // ── Socket state ──────────────────────────────────────────────────────────
    let mut socket_api = SocketApi::new();

    // Static socket storage for up to 256 concurrent smoltcp sockets.
    let mut sockets_storage: [SocketStorage; 256] = [SocketStorage::EMPTY; 256];
    let mut socket_set = SocketSet::new(&mut sockets_storage[..]);

    let mut last_link_state = device.link_up();

    // ── Main service loop ─────────────────────────────────────────────────────
    //
    // Design:
    // 1. iface.poll() drives smoltcp (calls device.receive() which non-blockingly
    //    drains the /dev/net/virtio0/rx VFS fd).
    // 2. net_provider.drain_rpcs() handles all pending /net/ VFS RPC messages from
    //    user applications (socket creates, connects, reads, writes, etc.).
    // 3. A second iface.poll() flushes any packets generated by RPC processing.
    // 4. port_wait on the /net/ provider port blocks until new RPCs arrive, keeping
    //    CPU usage low between application requests.
    //    NOTE: There is inherent polling latency for new Ethernet frames (~1 ms
    //    worst-case) since we can't port_wait on a VFS fd.  Future work: use a
    //    separate thread or an event-fd mechanism.
    loop {
        let mut did_work = false;

        // ── Phase 1: Poll smoltcp (ingests frames from /dev/net/virtio0/rx) ───
        let now = VfsNicDevice::now();
        iface.poll(now, &mut device, &mut socket_set);

        // ── Phase 2: Drain /net/ VFS RPC messages ────────────────────────────
        {
            let before_len = socket_api.socket_count();
            net_provider.drain_rpcs(&mut iface, &mut device, &mut socket_set, &mut socket_api);
            if socket_api.socket_count() != before_len {
                did_work = true;
            }
        }

        // ── Phase 3: Re-poll to flush packets created by RPCs ────────────────
        let now = VfsNicDevice::now();
        iface.poll(now, &mut device, &mut socket_set);

        // ── Phase 4: Sync link state ──────────────────────────────────────────
        let current_link = device.link_up();
        if current_link != last_link_state {
            last_link_state = current_link;
            net_provider.link_up = current_link;
            info!(
                "NETD: Link state changed → {}",
                if current_link { "UP" } else { "DOWN" }
            );
        }

        // ── Phase 5: Garbage-collect closed sockets ───────────────────────────
        socket_api.gc_closed_sockets(&mut socket_set);

        // ── Phase 6: Yield / wait ─────────────────────────────────────────────
        if !did_work {
            let wait_ports = [net_provider.req_read_port()];
            let _ = stem::syscall::port::port_wait(
                &wait_ports,
                abi::syscall::port_wait::READABLE,
            );
        }
    }
}

