[package]
name = "arch"
version.workspace = true
edition.workspace = true

[dependencies]
abi = { path = "../abi" }
kernel = { path = "../kernel" }
lazy_static = "1.4"
spin = "0.10.0"
runtime = { path = "../runtime", features = ["kernel"] }
thing_models = { path = "../thing_models" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.14"
