[package]
name = "arch"
version.workspace = true
edition.workspace = true

[dependencies]
abi = { path = "../abi" }
kernel_core = { path = "../kernel_core" }
lazy_static = "1.4"
spin = "0.10.0"
userland_rt = { path = "../userland_rt", features = ["kernel"] }
thing_models = { path = "../thing_models" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.14"
