[package]
name = "init"
version.workspace = true
edition.workspace = true

[lib]
name = "init"
path = "src/lib.rs"

[dependencies]
abi = { path = "../../abi" }
userland = { path = "../../userland" }
thing_models = { path = "../../thing_models" }
userland_std = { path = "../../userland_std" }
runtime = { path = "../../runtime" }

[features]
rootfs = []
