[package]
name = "kernel_x86_64"
version = "0.2.0"
edition = "2021"
license.workspace = true

[[bin]]
name = "kernel_x86_64"
test = false

[dependencies]
kernel_core = { path = "../../crates/kernel_core" }
bridge_x86_64 = { path = "../../crates/bridge_x86_64" }
hw = { path = "../../crates/hw" }
models = { path = "../../crates/models" }
linked_list_allocator = { version = "0.10", default-features = false, features = ["use_spin"] }
spin = "0.10"
limine = "0.5"
x86_64 = "0.15.4"
abi = { path = "../../crates/abi" }
postcard = { version = "1.0", default-features = false, features = ["alloc"] }
