//! BDD test runner task.

use crate::build::build;
use crate::common::{Result, rust_target};
use crate::image::build_iso;
use crate::limine::limine;
use crate::fetch::fetch;
use std::fs;
use xshell::{Shell, cmd};

/// Run BDD tests for one or more architectures.
pub fn bdd(
    sh: &Shell,
    feature: Option<String>,
    _tags: Option<String>,
    arches: Vec<String>,
) -> Result<()> {
    let mut results: Vec<(String, bool)> = Vec::new();

    for arch in &arches {
        match run_single_arch(sh, feature.as_deref(), arch) {
            Ok(()) => results.push((arch.clone(), true)),
            Err(e) => {
                eprintln!("Tests failed for {}: {}", arch, e);
                results.push((arch.clone(), false));
            }
        }
    }

    // Generate root README with links to all tested architectures
    generate_root_readme(&results)?;

    // Check if any tests failed
    let failed: Vec<_> = results.iter().filter(|(_, passed)| !passed).collect();
    if !failed.is_empty() {
        let failed_arches: Vec<_> = failed.iter().map(|(a, _)| a.as_str()).collect();
        return Err(format!("Tests failed for: {}", failed_arches.join(", ")).into());
    }

    println!("\n=== All tests passed for all architectures ===\n");
    Ok(())
}

/// Run BDD tests for a single architecture.
fn run_single_arch(sh: &Shell, feature: Option<&str>, arch: &str) -> Result<()> {
    // Install rustup target
    let target = rust_target(arch);
    println!("Ensuring rustup target {} is installed...", target);
    // Ignore errors - target may already be installed or use build-std
    let _ = cmd!(sh, "rustup target add {target}").run();

    // Build ISO
    println!("\n=== Building for {} ===\n", arch);
    fetch()?;
    limine(sh)?;
    build(sh, arch, "dev")?;
    build(sh, arch, "dev")?;
    let programs = crate::image::default_programs();
    build_iso(sh, arch, &programs)?;

    // Run tests
    println!("\n=== Running BDD tests for {} ===\n", arch);

    let mut cmd = std::process::Command::new("cargo");
    cmd.args(["run", "-p", "bdd"]);
    cmd.env("BDD_ARCH", arch);

    if let Some(f) = feature {
        cmd.env("BDD_FEATURE", f);
    }

    let status = cmd.spawn()?.wait()?;
    if !status.success() {
        return Err(format!("Tests failed for: {}", arch).into());
    }

    println!("\n=== Tests passed for {} ===\n", arch);
    Ok(())
}

/// Generate the root docs/behavior/README.md with links to all architecture results.
fn generate_root_readme(results: &[(String, bool)]) -> Result<()> {
    let docs_dir = std::path::PathBuf::from("docs/behavior");
    fs::create_dir_all(&docs_dir)?;

    let mut content = String::new();
    content.push_str("# Thing-OS BDD Test Results\n\n");
    content
        .push_str("Behavior-driven development test results organized by target architecture.\n\n");
    content.push_str("## Architectures\n\n");
    content.push_str("| Architecture | Status | Results |\n");
    content.push_str("|-------------|--------|--------|\n");

    for (arch, passed) in results {
        let status = if *passed { "✅ Passed" } else { "❌ Failed" };
        let link = format!("[📄 View Results](./{}/README.md)", arch);
        content.push_str(&format!("| {} | {} | {} |\n", arch, status, link));
    }

    content.push_str("\n---\n\n");
    content.push_str("*Generated by `just behave`*\n");

    let readme_path = docs_dir.join("README.md");
    fs::write(&readme_path, content)?;
    println!("Generated: {}", readme_path.display());

    Ok(())
}
