use std::path::Path;
use std::fs;

// Simple struct to hold extracted descriptors
#[derive(Debug)]
pub struct ThingDescriptor {
    pub struct_name: String,
    pub kind: String,
    pub schema: String,
    pub version: u32,
    pub fields: Vec<FieldDescriptor>,
}

#[derive(Debug)]
pub struct FieldDescriptor {
    pub name: String,
    pub type_name: String,
    pub is_option: bool,
}

pub fn generate(repo_root: &Path) -> Result<(), anyhow::Error> {
    println!("Generating ontology...");
    
    // 1. Scan crates/models/src for structs with #[derive(Thing)] and #[thing(...)]
    let models_dir = repo_root.join("crates/models/src");
    let descriptors = scan_models(&models_dir)?;
    
    // 2. Generate crates/symbols/src/generated.rs
    generate_symbols(&descriptors, repo_root)?;
    
    // 3. Generate crates/models/src/generated.rs (Glue)
    generate_glue(&descriptors, repo_root)?;
    
    // 4. Generate artifacts/ontology/ontology.bin
    generate_binary(&descriptors, repo_root)?;
    
    // 5. Generate ontology.lock
    generate_lock(&descriptors, repo_root)?;
    
    Ok(())
}

fn scan_models(dir: &Path) -> Result<Vec<ThingDescriptor>, anyhow::Error> {
    let mut descriptors = Vec::new();
    
    // Walk directory (assuming flat for now or recursive)
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().map_or(false, |e| e == "rs") {
            let content = fs::read_to_string(&path)?;
            let file = syn::parse_file(&content)?;
            
            for item in file.items {
                if let syn::Item::Struct(item_struct) = item {
                    if has_derive_thing(&item_struct) {
                        let attr = get_thing_attr(&item_struct).expect("Missing #[thing(...)] attribute");
                        let fields = extract_fields(&item_struct);
                        
                        descriptors.push(ThingDescriptor {
                            struct_name: item_struct.ident.to_string(),
                            kind: attr.kind,
                            schema: attr.schema,
                            version: attr.version,
                            fields,
                        });
                    }
                }
            }
        }
    }
    
    // Sort for determinism
    descriptors.sort_by(|a, b| a.kind.cmp(&b.kind));
    
    Ok(descriptors)
}

fn has_derive_thing(item: &syn::ItemStruct) -> bool {
    item.attrs.iter().any(|attr| {
        if let syn::Meta::List(meta) = &attr.meta {
            if meta.path.is_ident("derive") {
                return meta.tokens.to_string().contains("Thing");
            }
        }
        false
    })
}

struct ThingAttr {
    kind: String,
    schema: String,
    version: u32,
}

fn get_thing_attr(item: &syn::ItemStruct) -> Option<ThingAttr> {
    for attr in &item.attrs {
        if attr.path().is_ident("thing") {
            let mut kind = String::new();
            let mut schema = String::new();
            let mut version = 1;
            
            attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("kind") {
                    let value: syn::LitStr = meta.value()?.parse()?;
                    kind = value.value();
                } else if meta.path.is_ident("schema") {
                    let value: syn::LitStr = meta.value()?.parse()?;
                    schema = value.value();
                } else if meta.path.is_ident("version") {
                    let value: syn::LitInt = meta.value()?.parse()?;
                    version = value.base10_parse()?;
                }
                Ok(())
            }).ok()?;
            
            return Some(ThingAttr { kind, schema, version });
        }
    }
    None
}

fn extract_fields(item: &syn::ItemStruct) -> Vec<FieldDescriptor> {
    let mut fields = Vec::new();
    if let syn::Fields::Named(named) = &item.fields {
        for field in &named.named {
            let name = field.ident.as_ref().unwrap().to_string();
            let type_name = quote::quote!(#field.ty).to_string(); // Rough type string
            let is_option = type_name.starts_with("Option <") || type_name.starts_with("Option<");
            
            fields.push(FieldDescriptor {
                name,
                type_name, 
                is_option,
            });
        }
    }
    fields
}

/// FNV-1a 64-bit hash (duplicated from crates/abi/src/ids.rs for build tool usage)
const fn symbol_hash(s: &str) -> u64 {
    let mut hash: u64 = 0xcbf29ce484222325;
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        hash ^= bytes[i] as u64;
        hash = hash.wrapping_mul(0x100000001b3);
        i += 1;
    }
    hash
}

fn generate_symbols(descriptors: &[ThingDescriptor], root: &Path) -> Result<(), anyhow::Error> {
    let mut content = String::from("// Generated by xtask ontology\n\n");
    content.push_str("pub mod kind {\n    use abi::ids::SymbolId;\n");
    
    for desc in descriptors {
        let hash = symbol_hash(&desc.kind);
        let const_name = desc.kind.replace(".", "_").to_uppercase();
        content.push_str(&format!("    pub const {}: SymbolId = SymbolId(0x{:X});\n", const_name, hash));
    }
    content.push_str("}\n\n");
    
    content.push_str("pub mod schema {\n    use abi::ids::SymbolId;\n");
    for desc in descriptors {
        let hash = symbol_hash(&desc.schema);
        let const_name = desc.schema.replace(".", "_").to_uppercase();
        // Schema constants might need the version suffix handling in name if schema name is same but version differs?
        // Assuming unique schema names for now as per "schema.Window" vs "schema.Window@1" usually implies name + version in string?
        // The attribute has 'schema = "schema.Window"' and 'version = 1'.
        // The user said "schema.Window@1" as a canonical string.
        // I should probably construct the canonical string "name@version" if version > 0, or just use the name if it includes it.
        // The current models use `schema = "schema.Window"`, version = 1.
        // I will follow the user's hint: "schema.Window@1".
        
        // Wait, if I change the string to hash, I must ensure `kind(...)` and `schema(...)` methods return that hash.
        // Let's assume the attribute `schema` string IS the canonical base, and we append `@version`.
        // Or strictly follow the input. 
        // User example: `schema = "schema.Window"`, `version = 1`.
        // User text: "Canon strings must be exactly: ... schema.Window@1".
        // So I should format it.
        let canonical_schema = format!("{}@{}", desc.schema, desc.version);
        let hash = symbol_hash(&canonical_schema);
        
        // Constant name usually shouldn't include version unless necessary?
        // Let's stick to the base name for the constant for ergonomics, or include version if multiple.
        // For now: SCHEMA_WINDOW_V1 ?
        // Or just SCHEMA_WINDOW if we assume one version active?
        // Let's use SCHEMA_WINDOW and hope no collisions, or append _V{}.
        
        // Actually, let's keep it simple: Use the schema string from the attribute for the constant name, 
        // but hash the canonical string "name@version".
        content.push_str(&format!("    pub const {}: SymbolId = SymbolId(0x{:X});\n", const_name, hash));
    }
    content.push_str("}\n");
    
    fs::write(root.join("crates/symbols/src/generated.rs"), content)?;
    Ok(())
}

fn generate_glue(descriptors: &[ThingDescriptor], root: &Path) -> Result<(), anyhow::Error> {
    let mut content = String::from("// Generated by xtask ontology\n// SymbolId and ThingId are imported in lib.rs via abi::ids\n// Vec is imported in lib.rs\n\n");
    
    content.push_str("pub trait Thing {\n");
    content.push_str("    fn kind(&self) -> SymbolId;\n");
    content.push_str("    fn schema(&self) -> SymbolId;\n");
    content.push_str("    fn version(&self) -> u32;\n");
    content.push_str("    fn encode(&self) -> Vec<u8>;\n");
    content.push_str("    fn decode(bytes: &[u8]) -> Result<Self, ()> where Self: Sized;\n");
    content.push_str("}\n\n");
    
    for desc in descriptors {
        content.push_str(&format!("impl Thing for {} {{\n", desc.struct_name));
        
        let kind_hash = symbol_hash(&desc.kind);
        let canonical_schema = format!("{}@{}", desc.schema, desc.version);
        let schema_hash = symbol_hash(&canonical_schema);
        
        content.push_str(&format!("    fn kind(&self) -> SymbolId {{ SymbolId(0x{:X}) }}\n", kind_hash));
        content.push_str(&format!("    fn schema(&self) -> SymbolId {{ SymbolId(0x{:X}) }}\n", schema_hash));
        content.push_str(&format!("    fn version(&self) -> u32 {{ {} }}\n", desc.version));
        
        content.push_str("    fn encode(&self) -> Vec<u8> {\n");
        content.push_str("        let mut bytes = Vec::new();\n");
        for field in &desc.fields {
            if field.type_name.contains("SymbolId") {
                content.push_str(&format!("        bytes.extend_from_slice(&self.{}.0.to_le_bytes());\n", field.name));
            } else if field.type_name.contains("ThingId") {
                content.push_str(&format!("        bytes.extend_from_slice(&self.{}.0.to_le_bytes());\n", field.name));
            } else {
                 content.push_str(&format!("        bytes.extend_from_slice(&self.{}.to_le_bytes());\n", field.name));
            }
        }
        content.push_str("        bytes\n");
        content.push_str("    }\n");
        
        content.push_str("    fn decode(bytes: &[u8]) -> Result<Self, ()> {\n");
        content.push_str("        let mut offset = 0;\n");
        
        let mut fields_init = String::new();
        for field in &desc.fields {
             fields_init.push_str(&format!("        let {} = ", field.name));
             if field.type_name.contains("SymbolId") {
                 fields_init.push_str("SymbolId(u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?));\n");
                 fields_init.push_str("        offset += 8;\n");
             } else if field.type_name.contains("u64") || field.type_name.contains("i64") {
                 fields_init.push_str("u64::from_le_bytes(bytes[offset..offset+8].try_into().map_err(|_| ())?);\n");
                 if field.type_name.contains("i64") {
                     fields_init.push_str(&format!("        let {} = {} as i64;\n", field.name, field.name));
                 }
                 fields_init.push_str("        offset += 8;\n");
             } else if field.type_name.contains("u32") || field.type_name.contains("i32") {
                 fields_init.push_str("u32::from_le_bytes(bytes[offset..offset+4].try_into().map_err(|_| ())?);\n");
                 if field.type_name.contains("i32") {
                     fields_init.push_str(&format!("        let {} = {} as i32;\n", field.name, field.name));
                 }
                 fields_init.push_str("        offset += 4;\n");
             } else if field.type_name.contains("ThingId") {
                 fields_init.push_str("ThingId(u128::from_le_bytes(bytes[offset..offset+16].try_into().map_err(|_| ())?));\n");
                 fields_init.push_str("        offset += 16;\n");
             } else {
                 // Fallback or error for unknown types
                 fields_init.push_str("return Err(());\n");
             }
        }
        
        content.push_str(&fields_init);
        content.push_str("        Ok(Self {\n");
        for field in &desc.fields {
            content.push_str(&format!("            {},\n", field.name));
        }
        content.push_str("        })\n");
        content.push_str("    }\n");
        
        content.push_str("}\n\n");
    }
    
    fs::write(root.join("crates/models/src/generated.rs"), content)?;
    Ok(())
}

fn generate_binary(descriptors: &[ThingDescriptor], root: &Path) -> Result<(), anyhow::Error> {
    // Generate a simple binary format
    let content = format!("{:?}", descriptors); // Placeholder
    fs::write(root.join("artifacts/ontology/ontology.bin"), content)?;
    Ok(())
}

fn generate_lock(descriptors: &[ThingDescriptor], root: &Path) -> Result<(), anyhow::Error> {
    let mut content = String::from("# Ontology Lock File\n");
    content.push_str("# This file is generated by xtask. Do not edit manually.\n\n");
    
    content.push_str(&format!("count = {}\n", descriptors.len()));
    
    // We want a deterministic list
    for desc in descriptors {
        let canonical_schema = format!("{}@{}", desc.schema, desc.version);
        let schema_hash = symbol_hash(&canonical_schema);
        content.push_str(&format!("{} {} 0x{:X}\n", desc.kind, canonical_schema, schema_hash));
    }
    
    // Simple content digest
    let digest = symbol_hash(&content);
    let final_content = format!("digest = 0x{:X}\n\n{}", digest, content);
    
    fs::write(root.join("artifacts/ontology/ontology.lock"), final_content)?;
    Ok(())
}
