//! Build and package a stage-1 `rustc` cross-compiled to run on
//! `x86_64-unknown-thingos`, then stage it into the ISO root.
//!
//! # Environment variables
//! * `SKIP_RUSTC_THINGOS=1` – skip the build entirely (e.g. in CI where
//!   build time is constrained).
//!
//! # Caching
//! The build is considered up-to-date when both of these conditions hold:
//! 1. `target/rustc-thingos/rustc` exists.
//! 2. `target/rustc-thingos/.cache-key` contains a hash derived from the
//!    content of `targets/x86_64-unknown-thingos.json`, `rust-toolchain.toml`,
//!    and the git revision of `vendor/rust/`. Changing any of these
//!    invalidates the cache.

use crate::common::Result;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};
use xshell::{Shell, cmd};

/// Where the cached rustc binary lives (relative to the project root).
const RUSTC_BINARY: &str = "target/rustc-thingos/rustc";
/// Where the cache-key file lives.
const CACHE_KEY_FILE: &str = "target/rustc-thingos/.cache-key";
/// Output directory for all rustc-thingos build artifacts.
const OUTPUT_DIR: &str = "target/rustc-thingos";

// ---------------------------------------------------------------------------
// Cache-key helpers
// ---------------------------------------------------------------------------

fn compute_cache_key() -> String {
    let mut hasher = DefaultHasher::new();
    for path in &["targets/x86_64-unknown-thingos.json", "rust-toolchain.toml"] {
        if let Ok(content) = std::fs::read_to_string(path) {
            content.hash(&mut hasher);
        }
    }

    // Hash the current git revision of vendor/rust/ to invalidate the cache
    // when the fork is updated.
    if let Ok(output) = std::process::Command::new("git")
        .args(["rev-parse", "HEAD"])
        .current_dir("vendor/rust")
        .output()
    {
        if output.status.success() {
            output.stdout.hash(&mut hasher);
        }
    }

    format!("{:016x}", hasher.finish())
}

fn is_cache_valid() -> bool {
    if !Path::new(RUSTC_BINARY).exists() {
        return false;
    }
    match std::fs::read_to_string(CACHE_KEY_FILE) {
        Ok(stored) => stored.trim() == compute_cache_key(),
        Err(_) => false,
    }
}

fn write_cache_key() -> std::io::Result<()> {
    std::fs::write(CACHE_KEY_FILE, compute_cache_key())
}

// ---------------------------------------------------------------------------
// Bootstrap configuration
// ---------------------------------------------------------------------------

/// Generate a `config.toml` for `x.py` that cross-compiles stage-1 `rustc`
/// to run on `x86_64-unknown-thingos`.
fn bootstrap_config() -> String {
    // `build`  = the machine running the build
    // `host`   = the machine(s) the resulting compiler will *run* on
    // `target` = the machine(s) the resulting compiler can produce code for
    //
    // Setting host = ["x86_64-unknown-thingos"] instructs the bootstrap to
    // produce a rustc binary that is itself a thingos ELF (cross-compiled by
    // the stage-0 linux-gnu compiler).  RUST_TARGET_PATH must be set so that
    // x.py can locate our custom JSON spec.
    r#"change-id = "ignore"
# Auto-generated by `cargo xtask rustc-thingos` – do not edit by hand.
[build]
build = "x86_64-unknown-linux-gnu"
host  = ["x86_64-unknown-thingos"]
target = ["x86_64-unknown-thingos"]
local-rebuild = true
docs = false
compiler-docs = false

[rust]
optimize = true
debug-assertions = false
codegen-units = 1
lto = "off"

[llvm]
download-ci-llvm = true
"#
    .to_string()
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Build a stage-1 `rustc` cross-compiled to run on `x86_64-unknown-thingos`
/// and cache the result under `target/rustc-thingos/`.
///
/// Returns `Ok(None)` when the step is intentionally skipped (either via the
/// `SKIP_RUSTC_THINGOS=1` env-var or because the build is not yet supported
/// for the requested architecture).
///
/// The `arch` parameter guards the build: only `"x86_64"` is supported for
/// now; all other architectures silently return `Ok(None)`.
pub fn build_rustc_thingos(sh: &Shell, arch: &str) -> Result<Option<PathBuf>> {
    // Only x86_64 is supported at the moment.
    if arch != "x86_64" {
        return Ok(None);
    }

    // Honour the escape hatch env-var.
    if std::env::var("SKIP_RUSTC_THINGOS").as_deref() == Ok("1") {
        println!("SKIP_RUSTC_THINGOS=1 set – skipping rustc-thingos build.");
        return Ok(None);
    }

    // Fast path: cache is still valid.
    if is_cache_valid() {
        println!("rustc-thingos: cache hit, reusing {}", RUSTC_BINARY);
        return Ok(Some(PathBuf::from(RUSTC_BINARY)));
    }

    println!("rustc-thingos: building stage-1 rustc for x86_64-unknown-thingos …");
    println!("  (set SKIP_RUSTC_THINGOS=1 to skip this step)");

    // The Rust source tree is required.
    if !Path::new("vendor/rust/.git").exists() {
        return Err(
            "vendor/rust not found – run `just fetch-rust` first to clone the Rust source tree."
                .into(),
        );
    }

    std::fs::create_dir_all(OUTPUT_DIR)?;

    let cwd = std::env::current_dir()?;
    let rust_src = cwd.join("vendor/rust");
    let rust_src_str = rust_src.to_str().unwrap();

    // Write our bootstrap config.toml into the vendored source tree.
    std::fs::write(rust_src.join("config.toml"), bootstrap_config())?;

    // RUST_TARGET_PATH tells x.py where to find custom JSON target specs.
    let target_dir = cwd.join("targets");
    let target_dir_str = target_dir.to_str().unwrap();

    // Run the bootstrap.  Stage-1 is sufficient to produce a usable compiler;
    // a full stage-2 bootstrap can be added later.
    cmd!(
        sh,
        "python3 {rust_src_str}/x.py build --stage 1 compiler/rustc"
    )
    .env("RUST_TARGET_PATH", target_dir_str)
    .run()?;

    // Locate the cross-compiled rustc binary.  When the host triple is set to
    // thingos, x.py places the stage-1 compiler at:
    //   build/<build_triple>/stage1/bin/rustc
    // That binary is a thingos ELF produced by the stage-0 linux-gnu compiler.
    let stage1_rustc = rust_src.join("build/x86_64-unknown-linux-gnu/stage1/bin/rustc");

    if !stage1_rustc.exists() {
        // Fallback: search common stage-1 paths.
        let alt = rust_src
            .join("build")
            .join("x86_64-unknown-linux-gnu")
            .join("stage1-tools")
            .join("x86_64-unknown-thingos")
            .join("release")
            .join("rustc");
        if alt.exists() {
            sh.copy_file(&alt, RUSTC_BINARY)?;
        } else {
            return Err(
                format!(
                    "stage-1 rustc binary not found after bootstrap.\n\
                     Looked in:\n  {:?}\n  {:?}",
                    stage1_rustc, alt
                )
                .into(),
            );
        }
    } else {
        sh.copy_file(&stage1_rustc, RUSTC_BINARY)?;
    }

    write_cache_key()?;
    println!("rustc-thingos: binary cached at {}", RUSTC_BINARY);
    Ok(Some(PathBuf::from(RUSTC_BINARY)))
}

/// Copy the cached `rustc` binary (and the `rustlib` standard-library
/// artifacts) into the ISO root so they are available at runtime.
///
/// Placement:
/// * `/bin/rustc`            – the compiler binary
/// * `/usr/lib/rustlib/`     – standard-library rlibs for the thingos target
///
/// This is a no-op when `SKIP_RUSTC_THINGOS=1` is set or when no cached
/// binary is present (the ISO will simply not contain a compiler).
pub fn stage_rustc_for_iso(sh: &Shell, iso_root: &Path) -> Result<()> {
    if std::env::var("SKIP_RUSTC_THINGOS").as_deref() == Ok("1") {
        return Ok(());
    }

    let rustc_binary = Path::new(RUSTC_BINARY);
    if !rustc_binary.exists() {
        println!("rustc-thingos: no binary found, skipping ISO staging.");
        return Ok(());
    }

    // Stage the compiler binary at /bin/rustc.
    sh.copy_file(rustc_binary, iso_root.join("bin/rustc"))?;
    println!("  Staged /bin/rustc");

    // Stage the rustlib directory (contains rlibs needed to compile Rust
    // programs on the device) at /usr/lib/rustlib if it was produced.
    let cwd = std::env::current_dir()?;
    let rustlib_src =
        cwd.join("vendor/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib");
    if rustlib_src.exists() {
        sh.create_dir(iso_root.join("usr/lib"))?;
        let rustlib_src_str = rustlib_src.to_str().unwrap();
        let rustlib_dest_str = iso_root.join("usr/lib/rustlib").to_str().unwrap().to_string();
        cmd!(sh, "cp -r {rustlib_src_str} {rustlib_dest_str}").run()?;
        println!("  Staged /usr/lib/rustlib");
    }

    Ok(())
}
