[package]
name = "thing_codec"
version = "0.1.0"
edition = "2021"

[dependencies]
abi = { path = "../abi", default-features = false }
postcard = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[features]
default = []
std = ["abi/std", "postcard/use-std", "serde/std"]
alloc = ["serde/alloc", "postcard/alloc"]
