extern crate alloc;

use abi::hid::Key;

pub fn hid_to_evdev(key: Key) -> u32 {
    match key {
        Key::A => 30,
        Key::B => 48,
        Key::C => 46,
        Key::D => 32,
        Key::E => 18,
        Key::F => 33,
        Key::G => 34,
        Key::H => 35,
        Key::I => 23,
        Key::J => 36,
        Key::K => 37,
        Key::L => 38,
        Key::M => 50,
        Key::N => 49,
        Key::O => 24,
        Key::P => 25,
        Key::Q => 16,
        Key::R => 19,
        Key::S => 31,
        Key::T => 20,
        Key::U => 22,
        Key::V => 47,
        Key::W => 17,
        Key::X => 45,
        Key::Y => 21,
        Key::Z => 44,
        Key::Num1 => 2,
        Key::Num2 => 3,
        Key::Num3 => 4,
        Key::Num4 => 5,
        Key::Num5 => 6,
        Key::Num6 => 7,
        Key::Num7 => 8,
        Key::Num8 => 9,
        Key::Num9 => 10,
        Key::Num0 => 11,
        Key::Enter => 28,
        Key::Escape => 1,
        Key::Backspace => 14,
        Key::Tab => 15,
        Key::Space => 57,
        Key::Minus => 12,
        Key::Equal => 13,
        Key::LeftBracket => 26,
        Key::RightBracket => 27,
        Key::Backslash => 43,
        Key::Semicolon => 39,
        Key::Quote => 40,
        Key::Grave => 41,
        Key::Comma => 51,
        Key::Period => 52,
        Key::Slash => 53,
        Key::CapsLock => 58,
        Key::F1 => 59,
        Key::F2 => 60,
        Key::F3 => 61,
        Key::F4 => 62,
        Key::F5 => 63,
        Key::F6 => 64,
        Key::F7 => 65,
        Key::F8 => 66,
        Key::F9 => 67,
        Key::F10 => 68,
        Key::F11 => 87,
        Key::F12 => 88,
        Key::Insert => 110,
        Key::Home => 102,
        Key::PageUp => 104,
        Key::Delete => 111,
        Key::End => 107,
        Key::PageDown => 109,
        Key::Right => 106,
        Key::Left => 105,
        Key::Down => 108,
        Key::Up => 103,
        Key::LeftCtrl => 29,
        Key::LeftShift => 42,
        Key::LeftAlt => 56,
        Key::LeftMeta => 125,
        Key::RightCtrl => 97,
        Key::RightShift => 54,
        Key::RightAlt => 100,
        Key::RightMeta => 126,
        _ => 0,
    }
}

pub static XKB_KEYMAP: &str = concat!(
    "xkb_keymap {\n",
    "  xkb_keycodes \"evdev\" {\n",
    "    minimum = 8;\n",
    "    maximum = 255;\n",
    "    <ESC> = 9;\n",
    "    <AE01> = 10;\n",
    "    <AE02> = 11;\n",
    "    <AE03> = 12;\n",
    "    <AE04> = 13;\n",
    "    <AE05> = 14;\n",
    "    <AE06> = 15;\n",
    "    <AE07> = 16;\n",
    "    <AE08> = 17;\n",
    "    <AE09> = 18;\n",
    "    <AE10> = 19;\n",
    "    <AE11> = 20;\n",
    "    <AE12> = 21;\n",
    "    <BKSP> = 22;\n",
    "    <TAB> = 23;\n",
    "    <AD01> = 24;\n",
    "    <AD02> = 25;\n",
    "    <AD03> = 26;\n",
    "    <AD04> = 27;\n",
    "    <AD05> = 28;\n",
    "    <AD06> = 29;\n",
    "    <AD07> = 30;\n",
    "    <AD08> = 31;\n",
    "    <AD09> = 32;\n",
    "    <AD10> = 33;\n",
    "    <AD11> = 34;\n",
    "    <AD12> = 35;\n",
    "    <RTRN> = 36;\n",
    "    <LCTL> = 37;\n",
    "    <AC01> = 38;\n",
    "    <AC02> = 39;\n",
    "    <AC03> = 40;\n",
    "    <AC04> = 41;\n",
    "    <AC05> = 42;\n",
    "    <AC06> = 43;\n",
    "    <AC07> = 44;\n",
    "    <AC08> = 45;\n",
    "    <AC09> = 46;\n",
    "    <AC10> = 47;\n",
    "    <AC11> = 48;\n",
    "    <TLDE> = 49;\n",
    "    <LFSH> = 50;\n",
    "    <BKSL> = 51;\n",
    "    <AB01> = 52;\n",
    "    <AB02> = 53;\n",
    "    <AB03> = 54;\n",
    "    <AB04> = 55;\n",
    "    <AB05> = 56;\n",
    "    <AB06> = 57;\n",
    "    <AB07> = 58;\n",
    "    <AB08> = 59;\n",
    "    <AB09> = 60;\n",
    "    <AB10> = 61;\n",
    "    <RTSH> = 62;\n",
    "    <KPMU> = 63;\n",
    "    <LALT> = 64;\n",
    "    <SPCE> = 65;\n",
    "    <CAPS> = 66;\n",
    "    <FK01> = 67;\n",
    "    <FK02> = 68;\n",
    "    <FK03> = 69;\n",
    "    <FK04> = 70;\n",
    "    <FK05> = 71;\n",
    "    <FK06> = 72;\n",
    "    <FK07> = 73;\n",
    "    <FK08> = 74;\n",
    "    <FK09> = 75;\n",
    "    <FK10> = 76;\n",
    "    <HOME> = 110;\n",
    "    <UP> = 111;\n",
    "    <PGUP> = 112;\n",
    "    <LEFT> = 113;\n",
    "    <RGHT> = 114;\n",
    "    <END> = 115;\n",
    "    <DOWN> = 116;\n",
    "    <PGDN> = 117;\n",
    "    <INS> = 118;\n",
    "    <DELE> = 119;\n",
    "    <FK11> = 95;\n",
    "    <FK12> = 96;\n",
    "    <RCTL> = 105;\n",
    "    <RALT> = 108;\n",
    "    <LWIN> = 133;\n",
    "    <RWIN> = 134;\n",
    "  };\n",
    "  xkb_types \"complete\" {\n",
    "    virtual_modifiers NumLock,Alt,LevelThree,LAlt,RAlt,RAlt,ScrollLock,LevelFive,AltGr,Meta,Super,Hyper;\n",
    "    type \"ONE_LEVEL\" {\n",
    "      modifiers = none;\n",
    "      level_name[Level1] = \"Any\";\n",
    "    };\n",
    "    type \"TWO_LEVEL\" {\n",
    "      modifiers = Shift;\n",
    "      map[Shift] = Level2;\n",
    "      level_name[Level1] = \"Base\";\n",
    "      level_name[Level2] = \"Shift\";\n",
    "    };\n",
    "    type \"ALPHABETIC\" {\n",
    "      modifiers = Shift+Lock;\n",
    "      map[Shift] = Level2;\n",
    "      map[Lock] = Level2;\n",
    "      level_name[Level1] = \"Base\";\n",
    "      level_name[Level2] = \"Caps\";\n",
    "    };\n",
    "    type \"KEYPAD\" {\n",
    "      modifiers = Shift+NumLock;\n",
    "      map[NumLock] = Level2;\n",
    "      map[Shift] = Level2;\n",
    "      level_name[Level1] = \"Base\";\n",
    "      level_name[Level2] = \"Number\";\n",
    "    };\n",
    "  };\n",
    "  xkb_compatibility \"complete\" {\n",
    "    interpret Any+AnyOf(all) {\n",
    "      action = SetMods(modifiers=modMapMods,clearLocks);\n",
    "    };\n",
    "  };\n",
    "  xkb_symbols \"pc+us\" {\n",
    "    name[group1] = \"English (US)\";\n",
    "    key <ESC> { [ Escape ] };\n",
    "    key <AE01> { [ 1, exclam ] };\n",
    "    key <AE02> { [ 2, at ] };\n",
    "    key <AE03> { [ 3, numbersign ] };\n",
    "    key <AE04> { [ 4, dollar ] };\n",
    "    key <AE05> { [ 5, percent ] };\n",
    "    key <AE06> { [ 6, asciicircum ] };\n",
    "    key <AE07> { [ 7, ampersand ] };\n",
    "    key <AE08> { [ 8, asterisk ] };\n",
    "    key <AE09> { [ 9, parenleft ] };\n",
    "    key <AE10> { [ 0, parenright ] };\n",
    "    key <AE11> { [ minus, underscore ] };\n",
    "    key <AE12> { [ equal, plus ] };\n",
    "    key <BKSP> { [ BackSpace ] };\n",
    "    key <TAB> { [ Tab, ISO_Left_Tab ] };\n",
    "    key <AD01> { [ q, Q ] };\n",
    "    key <AD02> { [ w, W ] };\n",
    "    key <AD03> { [ e, E ] };\n",
    "    key <AD04> { [ r, R ] };\n",
    "    key <AD05> { [ t, T ] };\n",
    "    key <AD06> { [ y, Y ] };\n",
    "    key <AD07> { [ u, U ] };\n",
    "    key <AD08> { [ i, I ] };\n",
    "    key <AD09> { [ o, O ] };\n",
    "    key <AD10> { [ p, P ] };\n",
    "    key <AD11> { [ bracketleft, braceleft ] };\n",
    "    key <AD12> { [ bracketright, braceright ] };\n",
    "    key <RTRN> { [ Return ] };\n",
    "    key <LCTL> { [ Control_L ] };\n",
    "    key <AC01> { [ a, A ] };\n",
    "    key <AC02> { [ s, S ] };\n",
    "    key <AC03> { [ d, D ] };\n",
    "    key <AC04> { [ f, F ] };\n",
    "    key <AC05> { [ g, G ] };\n",
    "    key <AC06> { [ h, H ] };\n",
    "    key <AC07> { [ j, J ] };\n",
    "    key <AC08> { [ k, K ] };\n",
    "    key <AC09> { [ l, L ] };\n",
    "    key <AC10> { [ semicolon, colon ] };\n",
    "    key <AC11> { [ apostrophe, quotedbl ] };\n",
    "    key <TLDE> { [ grave, asciitilde ] };\n",
    "    key <LFSH> { [ Shift_L ] };\n",
    "    key <BKSL> { [ backslash, bar ] };\n",
    "    key <AB01> { [ z, Z ] };\n",
    "    key <AB02> { [ x, X ] };\n",
    "    key <AB03> { [ c, C ] };\n",
    "    key <AB04> { [ v, V ] };\n",
    "    key <AB05> { [ b, B ] };\n",
    "    key <AB06> { [ n, N ] };\n",
    "    key <AB07> { [ m, M ] };\n",
    "    key <AB08> { [ comma, less ] };\n",
    "    key <AB09> { [ period, greater ] };\n",
    "    key <AB10> { [ slash, question ] };\n",
    "    key <RTSH> { [ Shift_R ] };\n",
    "    key <LALT> { [ Alt_L, Meta_L ] };\n",
    "    key <SPCE> { [ space ] };\n",
    "    key <CAPS> { [ Caps_Lock ] };\n",
    "    key <FK01> { [ F1 ] };\n",
    "    key <FK02> { [ F2 ] };\n",
    "    key <FK03> { [ F3 ] };\n",
    "    key <FK04> { [ F4 ] };\n",
    "    key <FK05> { [ F5 ] };\n",
    "    key <FK06> { [ F6 ] };\n",
    "    key <FK07> { [ F7 ] };\n",
    "    key <FK08> { [ F8 ] };\n",
    "    key <FK09> { [ F9 ] };\n",
    "    key <FK10> { [ F10 ] };\n",
    "    key <FK11> { [ F11 ] };\n",
    "    key <FK12> { [ F12 ] };\n",
    "    key <HOME> { [ Home ] };\n",
    "    key <UP> { [ Up ] };\n",
    "    key <PGUP> { [ Prior ] };\n",
    "    key <LEFT> { [ Left ] };\n",
    "    key <RGHT> { [ Right ] };\n",
    "    key <END> { [ End ] };\n",
    "    key <DOWN> { [ Down ] };\n",
    "    key <PGDN> { [ Next ] };\n",
    "    key <INS> { [ Insert ] };\n",
    "    key <DELE> { [ Delete ] };\n",
    "    key <RCTL> { [ Control_R ] };\n",
    "    key <RALT> { [ Alt_R, Meta_R ] };\n",
    "    key <LWIN> { [ Super_L ] };\n",
    "    key <RWIN> { [ Super_R ] };\n",
    "    modifier_map Control { <LCTL>, <RCTL> };\n",
    "    modifier_map Shift { <LFSH>, <RTSH> };\n",
    "    modifier_map Mod1 { <LALT>, <RALT> };\n",
    "    modifier_map Lock { <CAPS> };\n",
    "    modifier_map Mod4 { <LWIN>, <RWIN> };\n",
    "  };\n",
    "};\n"
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hid_to_evdev_letters() {
        assert_eq!(hid_to_evdev(Key::A), 30);
        assert_eq!(hid_to_evdev(Key::Z), 44);
        assert_eq!(hid_to_evdev(Key::Q), 16);
    }

    #[test]
    fn test_hid_to_evdev_numbers() {
        assert_eq!(hid_to_evdev(Key::Num1), 2);
        assert_eq!(hid_to_evdev(Key::Num0), 11);
    }

    #[test]
    fn test_hid_to_evdev_special() {
        assert_eq!(hid_to_evdev(Key::Enter), 28);
        assert_eq!(hid_to_evdev(Key::Escape), 1);
        assert_eq!(hid_to_evdev(Key::Space), 57);
        assert_eq!(hid_to_evdev(Key::LeftCtrl), 29);
        assert_eq!(hid_to_evdev(Key::RightAlt), 100);
    }

    #[test]
    fn test_hid_to_evdev_function_keys() {
        assert_eq!(hid_to_evdev(Key::F1), 59);
        assert_eq!(hid_to_evdev(Key::F11), 87);
        assert_eq!(hid_to_evdev(Key::F12), 88);
    }

    #[test]
    fn test_hid_to_evdev_nav() {
        assert_eq!(hid_to_evdev(Key::Up), 103);
        assert_eq!(hid_to_evdev(Key::Down), 108);
        assert_eq!(hid_to_evdev(Key::Left), 105);
        assert_eq!(hid_to_evdev(Key::Right), 106);
        assert_eq!(hid_to_evdev(Key::Home), 102);
        assert_eq!(hid_to_evdev(Key::End), 107);
        assert_eq!(hid_to_evdev(Key::Delete), 111);
        assert_eq!(hid_to_evdev(Key::Insert), 110);
    }
}
