[package]
name = "debug_clock"
version.workspace = true
edition.workspace = true

[lib]
name = "debug_clock"
path = "src/lib.rs"

[dependencies]
runtime = { path = "../../runtime" }
thing_os = { path = "../../thing_os" }
abi = { path = "../../abi" }

[dev-dependencies]
kernel = { path = "../../kernel" }
abi = { path = "../../abi" }
