extern crate proc_macro;
use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, DeriveInput};

#[proc_macro_derive(Thing, attributes(thing))]
pub fn derive_thing(input: TokenStream) -> TokenStream {
    // This macro is primarily a marker for the ontology extraction tool.
    // However, it can also provide the `impl Thing` block if the glue code is
    // generated via macro expansion instead of file generation.
    //
    // For now, based on the plan, the glue code is generated by xtask into `generated.rs`.
    // So this macro just needs to pass through or generate a dummy impl to verify the attribute format.

    let _input = parse_macro_input!(input as DeriveInput);

    // We can emit an empty impl or a check.
    TokenStream::new()
}
