#!/usr/bin/env python3
"""
Generate builtin_font.rs from unifont.hex

Extracts ASCII printable glyphs (0x20-0x7E) and generates Rust static arrays.
Run: python3 tools/gen_builtin_font.py > crates/bloom/src/text/builtin_font.rs
"""

import sys
import os

# Path to unifont.hex relative to repo root
UNIFONT_PATH = "assets/fonts/unifont.hex"

def parse_unifont(path, start_cp=0x20, end_cp=0x7E):
    """Parse unifont.hex and extract glyphs for the given codepoint range."""
    glyphs = {}
    with open(path, 'r') as f:
        for line in f:
            line = line.strip()
            if ':' not in line:
                continue
            cp_hex, bitmap_hex = line.split(':', 1)
            try:
                cp = int(cp_hex, 16)
            except ValueError:
                continue
            if start_cp <= cp <= end_cp:
                # Convert hex string to bytes
                # Each glyph is 16 rows. 8px wide = 16 bytes, 16px wide = 32 bytes
                bmp_bytes = bytes.fromhex(bitmap_hex)
                glyphs[cp] = bmp_bytes
    return glyphs

def generate_rust(glyphs):
    """Generate Rust source code with static glyph data."""
    # For ASCII 0x20-0x7E, unifont uses 8px wide glyphs (16 bytes each)
    lines = []
    lines.append("//! Built-in bitmap font for immediate text rendering.")
    lines.append("//!")
    lines.append("//! This module provides a small embedded bitmap font extracted from Unifont")
    lines.append("//! covering ASCII 0x20-0x7E (printable characters). It allows Bloom to render")
    lines.append("//! text immediately at startup without waiting for font caching.")
    lines.append("//!")
    lines.append("//! Generated by: tools/gen_builtin_font.py")
    lines.append("")
    lines.append("use crate::painter::Painter;")
    lines.append("")
    lines.append("/// Glyph width in pixels (8px fixed for ASCII)")
    lines.append("pub const GLYPH_W: u32 = 8;")
    lines.append("")
    lines.append("/// Glyph height in pixels")
    lines.append("pub const GLYPH_H: u32 = 16;")
    lines.append("")
    lines.append("/// Number of glyphs (0x20 to 0x7E inclusive = 95 glyphs)")
    lines.append("const GLYPH_COUNT: usize = 95;")
    lines.append("")
    lines.append("/// First codepoint in the table")
    lines.append("const FIRST_CP: u8 = 0x20;")
    lines.append("")
    lines.append("/// Static bitmap data: 95 glyphs × 16 bytes each.")
    lines.append("/// Each byte is one row, MSB is leftmost pixel.")
    lines.append("static BITMAPS: [[u8; 16]; GLYPH_COUNT] = [")
    
    for cp in range(0x20, 0x7F):  # 0x20 to 0x7E inclusive
        if cp in glyphs:
            bmp = glyphs[cp]
            # Ensure it's 16 bytes (8px wide glyphs)
            if len(bmp) == 16:
                hex_bytes = ", ".join(f"0x{b:02X}" for b in bmp)
                char_repr = chr(cp) if 0x20 < cp < 0x7F else f"0x{cp:02X}"
                if cp == 0x20:
                    char_repr = "' '"
                elif cp == 0x5C:
                    char_repr = "'\\\\'"
                elif cp == 0x27:
                    char_repr = "'\\''"
                else:
                    char_repr = f"'{chr(cp)}'"
                lines.append(f"    [{hex_bytes}], // {char_repr}")
            elif len(bmp) == 32:
                # 16px wide glyph, take only first byte of each 2-byte row
                hex_bytes = ", ".join(f"0x{bmp[i*2]:02X}" for i in range(16))
                lines.append(f"    [{hex_bytes}], // '{chr(cp)}' (truncated)")
            else:
                # Fill with zeros for missing
                lines.append(f"    [0; 16], // '{chr(cp)}' (missing)")
        else:
            lines.append(f"    [0; 16], // 0x{cp:02X} (missing)")
    
    lines.append("];")
    lines.append("")
    lines.append("/// Get the bitmap for an ASCII character.")
    lines.append("///")
    lines.append("/// Returns None if the character is outside the supported range (0x20-0x7E).")
    lines.append("/// Each byte in the returned array is one row (MSB is leftmost pixel).")
    lines.append("#[inline]")
    lines.append("pub fn glyph_bitmap(ch: u8) -> Option<&'static [u8; 16]> {")
    lines.append("    if ch < FIRST_CP || ch > 0x7E {")
    lines.append("        return None;")
    lines.append("    }")
    lines.append("    Some(&BITMAPS[(ch - FIRST_CP) as usize])")
    lines.append("}")
    lines.append("")
    lines.append("/// Measure text width in pixels (monospace: 8px per character).")
    lines.append("#[inline]")
    lines.append("pub fn measure_text_ascii(s: &str) -> (u32, u32) {")
    lines.append("    let char_count = s.chars().take_while(|&c| c != '\\n').count() as u32;")
    lines.append("    (char_count * GLYPH_W, GLYPH_H)")
    lines.append("}")
    lines.append("")
    lines.append("/// Draw text using the built-in bitmap font.")
    lines.append("///")
    lines.append("/// Fast path for early boot when unifont cache isn't ready yet.")
    lines.append("pub fn draw_builtin_text(")
    lines.append("    painter: &mut dyn Painter,")
    lines.append("    mut x: i32,")
    lines.append("    y: i32,")
    lines.append("    color: u32,")
    lines.append("    text: &str,")
    lines.append(") {")
    lines.append("    let color_a = ((color >> 24) & 0xFF) as u8;")
    lines.append("    let color_r = ((color >> 16) & 0xFF) as u8;")
    lines.append("    let color_g = ((color >> 8) & 0xFF) as u8;")
    lines.append("    let color_b = (color & 0xFF) as u8;")
    lines.append("")
    lines.append("    for ch in text.bytes() {")
    lines.append("        if ch == b'\\n' {")
    lines.append("            break;")
    lines.append("        }")
    lines.append("")
    lines.append("        let Some(bitmap) = glyph_bitmap(ch) else {")
    lines.append("            // Skip unsupported characters, advance cursor")
    lines.append("            x += GLYPH_W as i32;")
    lines.append("            continue;")
    lines.append("        };")
    lines.append("")
    lines.append("        // Build pixel buffer for this glyph")
    lines.append("        let mut pixels = [0u32; (GLYPH_W * GLYPH_H) as usize];")
    lines.append("        for (row, &row_bits) in bitmap.iter().enumerate() {")
    lines.append("            for bit in 0..8 {")
    lines.append("                if (row_bits & (0x80 >> bit)) != 0 {")
    lines.append("                    let idx = row * 8 + bit;")
    lines.append("                    pixels[idx] = ((color_a as u32) << 24)")
    lines.append("                        | ((color_r as u32) << 16)")
    lines.append("                        | ((color_g as u32) << 8)")
    lines.append("                        | (color_b as u32);")
    lines.append("                }")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        painter.blit_rgba_alpha(x, y, &pixels, GLYPH_W, GLYPH_H);")
    lines.append("        x += GLYPH_W as i32;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    
    return "\n".join(lines)

def main():
    # Find repo root
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)  # tools/ -> repo root
    unifont_path = os.path.join(repo_root, UNIFONT_PATH)
    
    if not os.path.exists(unifont_path):
        print(f"Error: unifont.hex not found at {unifont_path}", file=sys.stderr)
        sys.exit(1)
    
    glyphs = parse_unifont(unifont_path)
    rust_code = generate_rust(glyphs)
    print(rust_code)

if __name__ == "__main__":
    main()
