[package]
name = "compositor"
version.workspace = true
edition.workspace = true

[lib]
name = "compositor"
path = "src/lib.rs"

[dependencies]
userland = { path = "../../userland" }
userland_rt = { path = "../../userland_rt" }
abi = { path = "../../abi" }
userland_std = { path = "../../userland_std" }
fontdue = { version = "0.9", default-features = false, features = ["hashbrown"] }
spin = { version = "0.9", default-features = false, features = ["once"] }

[dev-dependencies]
kernel = { path = "../../kernel" }
