[workspace]
resolver = "2"
members = [
  "crates/thing_std",
  "apps/clock",
  "apps/graph_dump",
  "drivers/ps2_keyboard",
  "apps/keylog",
]


[workspace.dependencies]
postcard = { version = "1", default-features = false, features = ["alloc"] }
serde = { version = "1", default-features = false, features = ["derive"] }

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
