use std::fs::File;
use std::io::{BufRead, BufReader, Write};
use std::collections::BTreeMap;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let unifont_hex_path = "/home/dancxjo/Documents/Projects/thing-os/assets/fonts/unifont.hex";
    let output_path = "/home/dancxjo/Documents/Projects/thing-os/userspace/bloom/src/builtin_font.rs";

    // Target codepoints from the original script
    let mut targets = Vec::new();
    for cp in 0x20..0x7F {
        targets.push(cp);
    }
    targets.extend_from_slice(&[
        0x2303, // ⌃
        0x2325, // ⌥
        0x21E7, // ⇧
        0x2318, // ⌘
        0x23CE, // ⏎
        0x232B, // ⌫
        0x21E5, // ⇥
        0x238B, // ⎋
        0x2190, // ←
        0x2191, // ↑
        0x2192, // →
        0x2193, // ↓
    ]);

    let mut glyph_data = BTreeMap::new();

    if !Path::new(unifont_hex_path).exists() {
        eprintln!("Error: unifont.hex not found at {}", unifont_hex_path);
        std::process::exit(1);
    }

    let file = File::open(unifont_hex_path)?;
    let reader = BufReader::new(file);

    for line in reader.lines() {
        let line = line?;
        let parts: Vec<&str> = line.split(':').collect();
        if parts.len() != 2 {
            continue;
        }

        if let Ok(cp) = u32::from_str_radix(parts[0], 16) {
            if targets.contains(&cp) {
                glyph_data.insert(cp, parts[1].trim().to_string());
            }
        }
    }

    let mut output = File::create(output_path)?;

    writeln!(output, "//! Built-in Unifont bitmap fallback font")?;
    writeln!(output, "//! This file is auto-generated by unifont-gen tool.")?;
    writeln!(output, "")?;
    writeln!(output, "pub struct BuiltinGlyph {{")?;
    writeln!(output, "    pub codepoint: u32,")?;
    writeln!(output, "    pub width: u8,")?;
    writeln!(output, "    pub bitmap: [u8; 32],")?;
    writeln!(output, "}}")?;
    writeln!(output, "")?;
    writeln!(output, "pub static BUILTIN_GLYPHS: &[BuiltinGlyph] = &[")?;

    for (cp, hex_data) in glyph_data {
        let mut bytes_data = Vec::new();
        for i in (0..hex_data.len()).step_by(2) {
            if let Ok(b) = u8::from_str_radix(&hex_data[i..i + 2], 16) {
                bytes_data.push(b);
            }
        }

        let width;
        let mut array_items = Vec::new();

        if bytes_data.len() == 16 {
            width = 8;
            for &b in &bytes_data {
                array_items.push(format!("0x{:02x}", b));
            }
            for _ in 0..16 {
                array_items.push("0x00".to_string());
            }
        } else if bytes_data.len() == 32 {
            width = 16;
            for &b in &bytes_data {
                array_items.push(format!("0x{:02x}", b));
            }
        } else {
            // Unexpected length, skip it
            continue;
        }

        writeln!(
            output,
            "    BuiltinGlyph {{ codepoint: {}, width: {}, bitmap: [{}] }}, // U+{:04X}",
            cp,
            width,
            array_items.join(", "),
            cp
        )?;
    }

    writeln!(output, "];")?;

    Ok(())
}
