[package]
name = "described"
version = "0.1.0"
edition = "2021"

[dependencies]
abi = { path = "../../abi" }
stem = { path = "../../stem" }
llm = { path = "../../libs/llm" }
blake3 = { version = "1.5", default-features = false, features = ["pure"] }

[dev-dependencies]
llm_stub = { path = "../../libs/llm_stub" }
